//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;

   public partial class Clima
   {
      public int Id { get; set; }

      [Required]
      public System.DateTime Fecha { get; set; }

      [Required]
      public decimal Temperatura { get; set; }

      [StringLength(maximumLength: 500, ErrorMessage = "Limite de 500 -caracteres")]
      public string Icono { get; set; }

      [Required]
      public int Humedad { get; set; }
      [Required]
      public int Viento { get; set; }
      [Required]
      public string Condicion { get; set; }
   }
}
