//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;

   public partial class ComentarioPrograma
   {
      public int Id { get; set; }

      [Required]
      public int UsuarioID { get; set; }

      [Required]
      public int ProgramaID { get; set; }

      [StringLength(maximumLength: int.MaxValue, ErrorMessage = "Limite de int.MaxValue caracteres")]
      [Required]
      public string Comentario { get; set; }

      public virtual ProgramaRadio ProgramaRadio { get; set; }
      public virtual Usuario Usuario { get; set; }
   }
}
