//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;

   public partial class CotizacionMoneda
   {
      public int Id { get; set; }

      [Required]
      public System.DateTime Fecha { get; set; }
      
      [StringLength(maximumLength: 50, ErrorMessage = "Limite de 50 caracteres")]
      [Required]
      public string TipoMoneda { get; set; }

      public decimal ValorCompra { get; set; }
      public decimal ValorVenta { get; set; }
   }
}
