//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;

   public partial class Noticia
   {
      public int Id { get; set; }

      [Required]
      [StringLength(maximumLength: 100, ErrorMessage = "Limite de 100 caracteres")]
      public string Titulo { get; set; }

      [StringLength(maximumLength: int.MaxValue, ErrorMessage = "Limite de int.MaxValue caracteres")]
      public string Contenido { get; set; }

      public System.DateTime FechaPublicacion { get; set; }

      [StringLength(maximumLength: 500, ErrorMessage = "Limite de 500 caracteres")]
      public string Imagen { get; set; }
   }
}
